# Generated by Django 4.2 on 2023-04-23 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("developers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("laptop", "Laptop"),
                            ("keyboard", "Keyboard"),
                            ("mouse", "Mouse"),
                            ("headset", "Headset"),
                            ("monitor", "Monitor"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="developers.developer",
                    ),
                ),
            ],
        ),
    ]
